# Generated by Django 5.1.3 on 2024-11-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('location', models.CharField(max_length=1000)),
                ('num_rooms', models.IntegerField()),
                ('type_building', models.CharField(max_length=1000)),
                ('bid', models.CharField(max_length=100)),
                ('num_floors', models.IntegerField()),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Users_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
            ],
        ),
    ]
